apiVersion: batch/v1
kind: Job
metadata:
  name: copy-model-job
  namespace: serving-model-env
spec:
  template:
    spec:
      containers:
      - name: copy-model
        image: ashutoshj/trained-model-image2
        command: ["/bin/sh", "-c"]
        args: ["cp -r /app/model/* /mnt/model/"]
        volumeMounts:
        - name: model-pv
          mountPath: /mnt/model
      restartPolicy: Never
      volumes:
      - name: model-pv
        persistentVolumeClaim:
          claimName: model-pvc-writer
  backoffLimit: 1