apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc-writer
  namespace: training-env
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: model-pv