# persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: train-model-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/model"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard