apiVersion: batch/v1
kind: Job
metadata:
  name: train-model-job
  namespace: training-model-env
spec:
  template:
    spec:
      containers:
      - name: trainer
        image: ashutoshj/training_image2
        volumeMounts:
        - name: model-volume
          mountPath: /mnt/model
      restartPolicy: Never
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: train-model-pvc