apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: train-model-pvc
  namespace: training-model-env
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: train-model-pv