apiVersion: batch/v1
kind: Job
metadata:
  name: jupyter-model-training
spec:
  template:
    spec:
      containers:
      - name: notebook-runner
        image: ashutosh.j/qna-model-training
        volumeMounts:
        - mountPath: /home/jovyan/work/output
          name: model-storage
        - mountPath: /home/jovyan/work
      restartPolicy: Never
      volumes:
      - name: checkpoint-storage
        persistentVolumeClaim:
          claimName: checkpoint-pvc

      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc
  backoffLimit: 1
