FROM python:3.8-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir torch==2.2.0+cpu torchaudio==2.2.0+cpu \
    -f https://download.pytorch.org/whl/torch_stable.html && \
    pip install --no-cache-dir transformers==4.39.0 fastapi uvicorn[standard]

WORKDIR /app

COPY qna_service.py /app/qna_service.py

EXPOSE 5000

CMD ["uvicorn" , "qna_service:app" , "--host" , "0.0.0.0" , "--port" , "5000"]